export let dados = [
    { email: 'guilherme@gmail', senha: '6767' },
    { email: 'lucas@gmail', senha: '4321' },
    { email: 'otario@gmail', senha: '0001' },
    { email: 'lustraMP@gmail', senha: '1000' },
    { email: 'mateus@gmail', senha: '1234'},
    { email: 'murilo@gmail', senha: '1234' },
    { email: 'timMaia@gmail', senha: '1234' },
    { email: 'thiago@gmail', senha: '1234' },
    { email: 'ayrtonSenna@gmail', senha: '1234' },
    { email: 'pedro@gmail', senha: '1234' },
    { email: 'hector@gmail', senha: '1234' },
    { email: 'guilherme@gmail', senha: '1234' },
    { email: 'lucas@gmail', senha: '1234' },
    { email: 'juan@gmail', senha: '1234' },
    { email: 'david@gmail', senha: '1234' },
    { email: 'taric@gmail', senha: '1234' },
    { email: 'alicia@gmail', senha: '1234' },
    { email: 'diego@gmail', senha: '1234' },
    { email: 'isa@gmail', senha: '1234' },
    { email: 'mariana@gmail', senha: '1234' },
    { email: 'andre@gmail', senha: '1234' },
];